---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	adapt_prompts(adapt_prompts)
	planning(planning)
	plan_review(plan_review)
	select_stage(select_stage)
	design(design)
	design_review(design_review)
	code_review(code_review)
	generate_code(generate_code)
	run_code(run_code)
	execution_check(execution_check)
	physics_check(physics_check)
	analyze(analyze)
	comparison_check(comparison_check)
	supervisor(supervisor)
	ask_user(ask_user)
	generate_report(generate_report)
	handle_backtrack(handle_backtrack)
	material_checkpoint(material_checkpoint)
	__end__([<p>__end__</p>]):::last
	__start__ --> adapt_prompts;
	adapt_prompts --> planning;
	analyze --> comparison_check;
	ask_user -.-> supervisor;
	code_review -.-> ask_user;
	code_review -.-> generate_code;
	code_review -.-> run_code;
	comparison_check -.-> analyze;
	comparison_check -.-> ask_user;
	comparison_check -.-> supervisor;
	design --> design_review;
	design_review -.-> ask_user;
	design_review -.-> design;
	design_review -.-> generate_code;
	execution_check -.-> ask_user;
	execution_check -.-> generate_code;
	execution_check -.-> physics_check;
	generate_code --> code_review;
	handle_backtrack --> select_stage;
	material_checkpoint -.-> ask_user;
	material_checkpoint -.-> select_stage;
	physics_check -.-> analyze;
	physics_check -.-> ask_user;
	physics_check -.-> design;
	physics_check -.-> generate_code;
	plan_review -.-> ask_user;
	plan_review -.-> planning;
	plan_review -.-> select_stage;
	planning -.-> plan_review;
	run_code --> execution_check;
	select_stage -.-> design;
	select_stage -.-> generate_report;
	supervisor -.-> ask_user;
	supervisor -.-> generate_report;
	supervisor -.-> handle_backtrack;
	supervisor -.-> material_checkpoint;
	supervisor -.-> planning;
	supervisor -.-> select_stage;
	generate_report --> __end__;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc

