# generated by datamodel-codegen:
#   filename:  assumptions_schema.json
#   timestamp: 2025-12-03T07:47:14+00:00

from __future__ import annotations

from typing import List, Literal, NotRequired, Optional, TypedDict


class GeometryInterpretation(TypedDict):
    id: str
    ambiguous_term: str
    interpretation: str
    reason: str
    confidence: NotRequired[Literal['high', 'medium', 'low']]
    introduced_by: NotRequired[str]
    stage_id: NotRequired[Optional[str]]


class Assumption(TypedDict):
    id: str
    category: Literal['material', 'geometry', 'source', 'boundary', 'numerical']
    description: str
    reason: str
    source: Literal[
        'paper_stated',
        'paper_inferred',
        'literature_default',
        'user_provided',
        'performance_optimization',
    ]
    alternatives_considered: NotRequired[List[str]]
    critical: bool
    validated: NotRequired[bool]
    validation_stage: NotRequired[Optional[str]]
    introduced_by: NotRequired[str]


class StageAssumption(Assumption):
    stage_id: str


class PaperReproductionAssumptions(TypedDict):
    paper_id: str
    global_assumptions: List[Assumption]
    geometry_interpretations: NotRequired[List[GeometryInterpretation]]
    stage_assumptions: NotRequired[List[StageAssumption]]
