# generated by datamodel-codegen:
#   filename:  code_reviewer_output_schema.json
#   timestamp: 2025-12-05T23:05:02+00:00

from __future__ import annotations

from typing import List, Literal, NotRequired, TypedDict, Union


class UnitNormalization(TypedDict):
    status: Literal['pass', 'fail', 'warning']
    a_unit_value: NotRequired[float]
    design_a_unit: NotRequired[float]
    match: NotRequired[bool]
    notes: NotRequired[str]


class Numerics(TypedDict):
    status: Literal['pass', 'fail', 'warning']
    notes: NotRequired[str]


class Source(TypedDict):
    status: Literal['pass', 'fail', 'warning']
    notes: NotRequired[str]


class Domain(TypedDict):
    status: Literal['pass', 'fail', 'warning']
    notes: NotRequired[str]


class Monitors(TypedDict):
    status: Literal['pass', 'fail', 'warning']
    notes: NotRequired[str]


class Visualization(TypedDict):
    status: Literal['pass', 'fail', 'warning']
    notes: NotRequired[str]


class CodeQuality(TypedDict):
    status: Literal['pass', 'fail', 'warning']
    has_plt_show: NotRequired[bool]
    has_input: NotRequired[bool]
    notes: NotRequired[str]


class Runtime(TypedDict):
    status: Literal['pass', 'fail', 'warning']
    estimated_minutes: NotRequired[float]
    budget_minutes: NotRequired[float]
    notes: NotRequired[str]


class MeepApi(TypedDict):
    status: Literal['pass', 'fail', 'warning']
    notes: NotRequired[str]


class OutputsCheckedItem(TypedDict):
    artifact_type: NotRequired[str]
    expected_filename: NotRequired[str]
    code_produces_file: NotRequired[bool]
    columns_match: NotRequired[bool]
    issues: NotRequired[str]


class ExpectedOutputs(TypedDict):
    status: Literal['pass', 'fail', 'warning']
    outputs_checked: NotRequired[List[OutputsCheckedItem]]
    all_outputs_accounted: bool
    notes: NotRequired[str]


class ChecklistResults(TypedDict):
    unit_normalization: UnitNormalization
    numerics: Numerics
    source: Source
    domain: Domain
    monitors: Monitors
    visualization: Visualization
    code_quality: CodeQuality
    runtime: Runtime
    meep_api: MeepApi
    expected_outputs: ExpectedOutputs


class Issue(TypedDict):
    severity: Literal['blocking', 'major', 'minor']
    category: Literal[
        'unit_normalization',
        'numerics',
        'source',
        'domain',
        'monitors',
        'visualization',
        'code_quality',
        'runtime',
        'meep_api',
        'expected_outputs',
    ]
    description: str
    suggested_fix: str
    code_location: NotRequired[str]


class BacktrackSuggestion(TypedDict):
    suggest_backtrack: bool
    target_stage_id: NotRequired[str]
    reason: NotRequired[str]
    severity: NotRequired[Literal['critical', 'significant', 'minor']]
    evidence: NotRequired[str]


class CodeReviewerAgentOutput(TypedDict):
    stage_id: str
    verdict: Literal['approve', 'needs_revision']
    checklist_results: ChecklistResults
    strengths: NotRequired[List[str]]
    issues: List[Issue]
    revision_count: NotRequired[int]
    escalate_to_user: NotRequired[Union[bool, str]]
    backtrack_suggestion: NotRequired[BacktrackSuggestion]
    summary: str
