# generated by datamodel-codegen:
#   filename:  code_generator_output_schema.json
#   timestamp: 2025-12-03T07:47:14+00:00

from __future__ import annotations

from typing import List, Literal, NotRequired, Optional, TypedDict


class UnitSystemUsed(TypedDict):
    characteristic_length_m: NotRequired[float]
    verified_from_design: NotRequired[bool]


class MaterialsUsedItem(TypedDict):
    material_name: NotRequired[str]
    source: NotRequired[str]
    data_file_path: NotRequired[Optional[str]]


class ExpectedOutput(TypedDict):
    artifact_type: Literal[
        'spectrum_csv',
        'field_data_npz',
        'field_plot_png',
        'spectrum_plot_png',
        'dispersion_csv',
        'raw_h5',
        'result_json',
    ]
    filename: str
    description: str
    columns: NotRequired[List[str]]
    target_figure: NotRequired[Optional[str]]


class SafetyChecks(TypedDict):
    no_plt_show: NotRequired[bool]
    no_input: NotRequired[bool]
    uses_plt_savefig_close: NotRequired[bool]
    relative_paths_only: NotRequired[bool]
    includes_result_json: NotRequired[bool]


class DesignCompliance(TypedDict):
    unit_system_matches_design: NotRequired[bool]
    geometry_matches_design: NotRequired[bool]
    materials_match_design: NotRequired[bool]
    output_filenames_match_spec: NotRequired[bool]


class CodeGeneratorAgentOutput(TypedDict):
    stage_id: str
    code: str
    code_summary: NotRequired[str]
    unit_system_used: NotRequired[UnitSystemUsed]
    materials_used: NotRequired[List[MaterialsUsedItem]]
    expected_outputs: List[ExpectedOutput]
    estimated_runtime_minutes: float
    estimated_memory_gb: NotRequired[float]
    dependencies_used: NotRequired[List[str]]
    progress_markers: NotRequired[List[str]]
    safety_checks: NotRequired[SafetyChecks]
    design_compliance: NotRequired[DesignCompliance]
    revision_notes: NotRequired[Optional[str]]
