# generated by datamodel-codegen:
#   filename:  design_reviewer_output_schema.json
#   timestamp: 2025-12-05T23:05:02+00:00

from __future__ import annotations

from typing import List, Literal, NotRequired, TypedDict, Union


class Geometry(TypedDict):
    status: Literal['pass', 'fail', 'warning']
    notes: NotRequired[str]


class Physics(TypedDict):
    status: Literal['pass', 'fail', 'warning']
    notes: NotRequired[str]


class Materials(TypedDict):
    status: Literal['pass', 'fail', 'warning']
    notes: NotRequired[str]


class UnitSystem(TypedDict):
    status: Literal['pass', 'fail', 'warning']
    a_unit_value: NotRequired[float]
    notes: NotRequired[str]


class Source(TypedDict):
    status: Literal['pass', 'fail', 'warning']
    notes: NotRequired[str]


class Domain(TypedDict):
    status: Literal['pass', 'fail', 'warning']
    notes: NotRequired[str]


class Resolution(TypedDict):
    status: Literal['pass', 'fail', 'warning']
    notes: NotRequired[str]


class Outputs(TypedDict):
    status: Literal['pass', 'fail', 'warning']
    notes: NotRequired[str]


class Runtime(TypedDict):
    status: Literal['pass', 'fail', 'warning']
    estimated_minutes: NotRequired[float]
    budget_minutes: NotRequired[float]
    notes: NotRequired[str]


class ChecklistResults(TypedDict):
    geometry: Geometry
    physics: Physics
    materials: Materials
    unit_system: UnitSystem
    source: Source
    domain: Domain
    resolution: Resolution
    outputs: Outputs
    runtime: Runtime


class Issue(TypedDict):
    severity: Literal['blocking', 'major', 'minor']
    category: Literal[
        'geometry',
        'physics',
        'materials',
        'unit_system',
        'source',
        'domain',
        'resolution',
        'outputs',
        'runtime',
    ]
    description: str
    suggested_fix: str


class BacktrackSuggestion(TypedDict):
    suggest_backtrack: bool
    target_stage_id: NotRequired[str]
    reason: NotRequired[str]
    severity: NotRequired[Literal['critical', 'significant', 'minor']]
    evidence: NotRequired[str]


class DesignReviewerAgentOutput(TypedDict):
    stage_id: str
    verdict: Literal['approve', 'needs_revision']
    checklist_results: ChecklistResults
    strengths: NotRequired[List[str]]
    issues: List[Issue]
    revision_count: NotRequired[int]
    escalate_to_user: NotRequired[Union[bool, str]]
    backtrack_suggestion: NotRequired[BacktrackSuggestion]
    summary: str
