# generated by datamodel-codegen:
#   filename:  execution_validator_output_schema.json
#   timestamp: 2025-12-05T23:05:02+00:00

from __future__ import annotations

from typing import List, Literal, NotRequired, Optional, TypedDict


class ExecutionStatus(TypedDict):
    completed: bool
    exit_code: NotRequired[int]
    runtime_seconds: NotRequired[float]
    memory_peak_mb: NotRequired[float]
    timed_out: NotRequired[bool]


class SpecComplianceItem(TypedDict):
    artifact_type: NotRequired[str]
    expected_filename: NotRequired[str]
    actual_filename: NotRequired[Optional[str]]
    exists: NotRequired[bool]
    non_empty: NotRequired[bool]
    valid_format: NotRequired[bool]
    columns_match: NotRequired[bool]
    issues: NotRequired[List[str]]


class FilesCheck(TypedDict):
    expected_files: List[str]
    found_files: List[str]
    missing_files: List[str]
    all_present: bool
    spec_compliance: NotRequired[List[SpecComplianceItem]]


class SuspiciousValue(TypedDict):
    file: NotRequired[str]
    issue: NotRequired[str]


class DataQuality(TypedDict):
    nan_detected: NotRequired[bool]
    inf_detected: NotRequired[bool]
    negative_where_unexpected: NotRequired[bool]
    suspicious_values: NotRequired[List[SuspiciousValue]]


class ErrorsDetectedItem(TypedDict):
    error_type: str
    message: str
    location: NotRequired[str]
    severity: NotRequired[Literal['critical', 'warning', 'info']]


class ExecutionValidatorAgentOutput(TypedDict):
    stage_id: str
    verdict: Literal['pass', 'warning', 'fail']
    execution_status: ExecutionStatus
    files_check: FilesCheck
    data_quality: NotRequired[DataQuality]
    errors_detected: NotRequired[List[ErrorsDetectedItem]]
    warnings: NotRequired[List[str]]
    stdout_summary: NotRequired[str]
    stderr_summary: NotRequired[str]
    recovery_suggestion: NotRequired[str]
    summary: str
