# generated by datamodel-codegen:
#   filename:  metrics_schema.json
#   timestamp: 2025-12-05T23:05:02+00:00

from __future__ import annotations

from typing import Dict, List, Literal, NotRequired, Optional, TypedDict


class AgentCall(TypedDict):
    agent: Literal[
        'PromptAdaptorAgent',
        'PlannerAgent',
        'SimulationDesignerAgent',
        'CodeGeneratorAgent',
        'CodeReviewerAgent',
        'ExecutionValidatorAgent',
        'PhysicsSanityAgent',
        'ResultsAnalyzerAgent',
        'ComparisonValidatorAgent',
        'SupervisorAgent',
    ]
    node: NotRequired[str]
    stage_id: NotRequired[Optional[str]]
    timestamp: str
    duration_seconds: float
    input_tokens: NotRequired[Optional[int]]
    output_tokens: NotRequired[Optional[int]]
    model: NotRequired[Optional[str]]
    verdict: NotRequired[Optional[str]]
    error: NotRequired[Optional[str]]


class StageMetric(TypedDict):
    stage_id: str
    stage_type: Literal[
        'MATERIAL_VALIDATION',
        'SINGLE_STRUCTURE',
        'ARRAY_SYSTEM',
        'PARAMETER_SWEEP',
        'COMPLEX_PHYSICS',
    ]
    started_at: NotRequired[Optional[str]]
    completed_at: NotRequired[Optional[str]]
    duration_seconds: NotRequired[Optional[float]]
    simulation_runtime_seconds: NotRequired[Optional[float]]
    design_revisions: NotRequired[int]
    code_revisions: NotRequired[int]
    analysis_revisions: NotRequired[int]
    final_status: NotRequired[
        Literal['success', 'partial', 'failure', 'blocked', 'skipped']
    ]
    escalated_to_user: NotRequired[bool]


class RevisionReason(TypedDict):
    category: NotRequired[str]
    count: NotRequired[int]


class RevisionSummary(TypedDict):
    total_design_revisions: NotRequired[int]
    total_code_revisions: NotRequired[int]
    total_analysis_revisions: NotRequired[int]
    replans: NotRequired[int]
    user_interventions: NotRequired[int]
    revision_reasons: NotRequired[List[RevisionReason]]


class ByAgent(TypedDict):
    input_tokens: NotRequired[int]
    output_tokens: NotRequired[int]
    call_count: NotRequired[int]


class ByModel(TypedDict):
    input_tokens: NotRequired[int]
    output_tokens: NotRequired[int]
    call_count: NotRequired[int]


class TokenSummary(TypedDict):
    total_input_tokens: NotRequired[int]
    total_output_tokens: NotRequired[int]
    by_agent: NotRequired[Dict[str, ByAgent]]
    by_model: NotRequired[Dict[str, ByModel]]


class AdaptationTypes(TypedDict):
    append: NotRequired[int]
    modify: NotRequired[int]
    disable: NotRequired[int]


class PromptAdaptations(TypedDict):
    adaptations_count: NotRequired[int]
    agents_modified: NotRequired[List[str]]
    adaptation_types: NotRequired[AdaptationTypes]


class ReproductionQuality(TypedDict):
    figures_targeted: NotRequired[int]
    figures_reproduced: NotRequired[int]
    success_count: NotRequired[int]
    partial_count: NotRequired[int]
    failure_count: NotRequired[int]
    success_rate: NotRequired[float]


class ReproductionMetrics(TypedDict):
    paper_id: str
    started_at: str
    completed_at: NotRequired[Optional[str]]
    total_duration_seconds: NotRequired[Optional[float]]
    final_status: NotRequired[
        Literal['in_progress', 'completed', 'stopped_by_user', 'failed']
    ]
    agent_calls: List[AgentCall]
    stage_metrics: List[StageMetric]
    revision_summary: NotRequired[RevisionSummary]
    token_summary: NotRequired[TokenSummary]
    prompt_adaptations: NotRequired[PromptAdaptations]
    reproduction_quality: NotRequired[ReproductionQuality]
