# generated by datamodel-codegen:
#   filename:  physics_sanity_output_schema.json
#   timestamp: 2025-12-05T23:05:02+00:00

from __future__ import annotations

from typing import List, Literal, NotRequired, TypedDict, Union


class ConservationCheck(TypedDict):
    law: str
    status: Literal['pass', 'warning', 'fail']
    expected_value: NotRequired[float]
    actual_value: NotRequired[float]
    deviation_percent: NotRequired[float]
    threshold_percent: NotRequired[float]
    notes: NotRequired[str]


class ExpectedRange(TypedDict):
    min: NotRequired[float]
    max: NotRequired[float]


class ValueRangeCheck(TypedDict):
    quantity: str
    status: Literal['pass', 'warning', 'fail']
    value: NotRequired[float]
    expected_range: NotRequired[ExpectedRange]
    notes: NotRequired[str]


class NumericalQuality(TypedDict):
    field_decay_achieved: NotRequired[bool]
    convergence_observed: NotRequired[bool]
    artifacts_detected: NotRequired[List[str]]
    notes: NotRequired[str]


class PhysicalPlausibility(TypedDict):
    resonance_positions_reasonable: NotRequired[bool]
    linewidths_reasonable: NotRequired[bool]
    magnitude_scale_reasonable: NotRequired[bool]
    spectral_features_expected: NotRequired[bool]
    concerns: NotRequired[List[str]]


class Concern(TypedDict):
    concern: str
    severity: Literal['critical', 'moderate', 'minor']
    possible_cause: NotRequired[str]
    suggested_action: NotRequired[str]


class BacktrackSuggestion(TypedDict):
    suggest_backtrack: bool
    target_stage_id: NotRequired[str]
    reason: NotRequired[str]
    severity: NotRequired[Literal['critical', 'significant', 'minor']]
    evidence: NotRequired[str]


class PhysicsSanityAgentOutput(TypedDict):
    stage_id: str
    verdict: Literal['pass', 'warning', 'fail', 'design_flaw']
    conservation_checks: List[ConservationCheck]
    value_range_checks: List[ValueRangeCheck]
    numerical_quality: NotRequired[NumericalQuality]
    physical_plausibility: NotRequired[PhysicalPlausibility]
    concerns: NotRequired[List[Concern]]
    escalate_to_user: NotRequired[Union[bool, str]]
    backtrack_suggestion: NotRequired[BacktrackSuggestion]
    summary: str
