# generated by datamodel-codegen:
#   filename:  planner_output_schema.json
#   timestamp: 2025-12-05T23:05:02+00:00

from __future__ import annotations

from typing import List, Literal, NotRequired, Optional, TypedDict, Union


class SkippedFigure(TypedDict):
    figure_id: str
    reason: str
    classification: Literal[
        'not_reproducible', 'reproducible_other', 'out_of_scope', 'low_priority'
    ]


class ReproductionScope(TypedDict):
    total_figures: NotRequired[int]
    reproducible_figures: NotRequired[int]
    attempted_figures: NotRequired[List[str]]
    skipped_figures: NotRequired[List[SkippedFigure]]
    coverage_percent: NotRequired[float]


class ExtractedParameter(TypedDict):
    name: str
    value: Union[float, str, List[float]]
    unit: str
    source: Literal[
        'text',
        'figure_caption',
        'figure_axis',
        'supplementary',
        'inferred',
        'user_correction',
    ]
    location: NotRequired[str]
    cross_checked: NotRequired[bool]
    discrepancy_notes: NotRequired[Optional[str]]


class Target(TypedDict):
    figure_id: str
    description: str
    type: Literal['spectrum', 'dispersion', 'field_map', 'parameter_sweep', 'other']
    simulation_class: Literal[
        'FDTD_DIRECT',
        'FDTD_DERIVED',
        'ANALYTICAL',
        'COMPLEX_PHYSICS',
        'NOT_REPRODUCIBLE',
    ]
    complexity_notes: NotRequired[Optional[str]]
    precision_requirement: NotRequired[
        Literal['excellent', 'good', 'acceptable', 'qualitative']
    ]
    digitized_data_path: NotRequired[Optional[str]]


class ExpectedOutput(TypedDict):
    artifact_type: Literal[
        'spectrum_csv',
        'field_data_npz',
        'field_plot_png',
        'spectrum_plot_png',
        'dispersion_csv',
        'raw_h5',
    ]
    filename_pattern: str
    description: str
    columns: NotRequired[List[str]]
    target_figure: NotRequired[str]


class Stage(TypedDict):
    stage_id: str
    stage_type: Literal[
        'MATERIAL_VALIDATION',
        'SINGLE_STRUCTURE',
        'ARRAY_SYSTEM',
        'PARAMETER_SWEEP',
        'COMPLEX_PHYSICS',
    ]
    name: str
    description: str
    targets: List[str]
    dependencies: List[str]
    is_mandatory_validation: NotRequired[bool]
    complexity_class: NotRequired[
        Literal[
            'analytical', '2D_light', '2D_medium', '3D_light', '3D_medium', '3D_heavy'
        ]
    ]
    runtime_estimate_minutes: NotRequired[float]
    runtime_budget_minutes: NotRequired[float]
    max_revisions: NotRequired[int]
    fallback_strategy: NotRequired[Literal['ask_user', 'simplify', 'skip_with_warning']]
    validation_criteria: NotRequired[List[str]]
    expected_outputs: NotRequired[List[ExpectedOutput]]
    reference_data_path: NotRequired[Optional[str]]


class GlobalAssumption(TypedDict):
    id: str
    category: Literal['material', 'geometry', 'source', 'boundary', 'numerical']
    description: str
    reason: str
    source: Literal[
        'paper_stated', 'paper_inferred', 'literature_default', 'user_provided'
    ]
    alternatives_considered: NotRequired[List[str]]
    critical: NotRequired[bool]
    validated: NotRequired[bool]
    validation_stage: NotRequired[Optional[str]]


class GeometryInterpretation(TypedDict):
    term: NotRequired[str]
    interpretation: NotRequired[str]
    alternatives: NotRequired[List[str]]
    confidence: NotRequired[Literal['high', 'medium', 'low']]


class Assumptions(TypedDict):
    global_assumptions: NotRequired[List[GlobalAssumption]]
    geometry_interpretations: NotRequired[List[GeometryInterpretation]]


class Stage2(TypedDict):
    stage_id: NotRequired[str]
    status: NotRequired[
        Literal[
            'not_started',
            'in_progress',
            'completed_success',
            'completed_partial',
            'completed_failed',
            'blocked',
            'needs_rerun',
            'invalidated',
        ]
    ]
    summary: NotRequired[str]


class Progress(TypedDict):
    stages: NotRequired[List[Stage2]]


class BlockingIssue(TypedDict):
    description: str
    question_for_user: str


class PlannedMaterial(TypedDict):
    material_id: NotRequired[str]
    name: NotRequired[str]
    suggested_source: NotRequired[str]
    path: NotRequired[Optional[str]]


class PlannerAgentOutput(TypedDict):
    paper_id: str
    paper_domain: Literal[
        'plasmonics',
        'photonic_crystal',
        'metamaterial',
        'thin_film',
        'waveguide',
        'strong_coupling',
        'nonlinear',
        'other',
    ]
    title: str
    summary: str
    main_system: NotRequired[str]
    main_claims: NotRequired[List[str]]
    simulation_approach: NotRequired[str]
    reproduction_scope: NotRequired[ReproductionScope]
    extracted_parameters: List[ExtractedParameter]
    targets: List[Target]
    stages: List[Stage]
    assumptions: Assumptions
    progress: Progress
    staging_rationale: NotRequired[str]
    blocking_issues: NotRequired[List[BlockingIssue]]
    planned_materials: NotRequired[List[PlannedMaterial]]
