# generated by datamodel-codegen:
#   filename:  plan_schema.json
#   timestamp: 2025-12-03T07:47:14+00:00

from __future__ import annotations

from typing import List, Literal, NotRequired, Optional, TypedDict, Union


class SkippedFigure(TypedDict):
    figure_id: str
    reason: str
    classification: Literal[
        'not_reproducible', 'reproducible_other', 'out_of_scope', 'low_priority'
    ]


class ReproductionScope(TypedDict):
    total_figures: NotRequired[int]
    reproducible_figures: NotRequired[int]
    reproducible_figure_ids: NotRequired[List[str]]
    attempted_figures: NotRequired[List[str]]
    skipped_figures: NotRequired[List[SkippedFigure]]
    coverage_percent: NotRequired[float]


class ExtractedParameter(TypedDict):
    name: str
    value: Union[float, str, List[float]]
    unit: str
    source: Literal[
        'text', 'figure_caption', 'figure_axis', 'supplementary', 'inferred'
    ]
    location: NotRequired[str]
    cross_checked: NotRequired[bool]
    discrepancy_notes: NotRequired[Optional[str]]


class Target(TypedDict):
    figure_id: str
    description: str
    type: Literal['spectrum', 'dispersion', 'field_map', 'parameter_sweep', 'other']
    simulation_class: Literal[
        'FDTD_DIRECT',
        'FDTD_DERIVED',
        'ANALYTICAL',
        'COMPLEX_PHYSICS',
        'NOT_REPRODUCIBLE',
    ]
    complexity_notes: NotRequired[Optional[str]]
    precision_requirement: NotRequired[
        Literal['excellent', 'good', 'acceptable', 'qualitative']
    ]
    digitized_data_path: NotRequired[Optional[str]]


class ExpectedOutput(TypedDict):
    artifact_type: Literal[
        'spectrum_csv',
        'field_data_npz',
        'field_plot_png',
        'spectrum_plot_png',
        'dispersion_csv',
        'raw_h5',
    ]
    filename_pattern: str
    description: str
    columns: NotRequired[List[str]]
    target_figure: NotRequired[str]


class Stage(TypedDict):
    stage_id: str
    stage_type: Literal[
        'MATERIAL_VALIDATION',
        'SINGLE_STRUCTURE',
        'ARRAY_SYSTEM',
        'PARAMETER_SWEEP',
        'COMPLEX_PHYSICS',
    ]
    name: str
    description: str
    targets: List[str]
    dependencies: List[str]
    is_mandatory_validation: NotRequired[bool]
    complexity_class: NotRequired[
        Literal[
            'analytical', '2D_light', '2D_medium', '3D_light', '3D_medium', '3D_heavy'
        ]
    ]
    runtime_estimate_minutes: NotRequired[float]
    runtime_budget_minutes: NotRequired[float]
    max_revisions: NotRequired[int]
    fallback_strategy: NotRequired[Literal['ask_user', 'simplify', 'skip_with_warning']]
    validation_criteria: NotRequired[List[str]]
    expected_outputs: NotRequired[List[ExpectedOutput]]
    reference_data_path: NotRequired[Optional[str]]


class PaperReproductionPlan(TypedDict):
    paper_id: str
    paper_domain: Literal[
        'plasmonics',
        'photonic_crystal',
        'metamaterial',
        'thin_film',
        'waveguide',
        'strong_coupling',
        'nonlinear',
        'other',
    ]
    title: str
    summary: str
    main_system: NotRequired[str]
    main_claims: NotRequired[List[str]]
    simulation_approach: NotRequired[str]
    reproduction_scope: NotRequired[ReproductionScope]
    extracted_parameters: NotRequired[List[ExtractedParameter]]
    targets: List[Target]
    stages: List[Stage]
