# generated by datamodel-codegen:
#   filename:  plan_reviewer_output_schema.json
#   timestamp: 2025-12-03T07:47:14+00:00

from __future__ import annotations

from typing import List, Literal, NotRequired, TypedDict, Union


class Coverage(TypedDict):
    status: Literal['pass', 'fail', 'warning']
    figures_covered: NotRequired[List[str]]
    figures_missing: NotRequired[List[str]]
    notes: NotRequired[str]


class DigitizedData(TypedDict):
    status: Literal['pass', 'fail', 'warning']
    excellent_targets: NotRequired[List[str]]
    have_digitized: NotRequired[List[str]]
    missing_digitized: NotRequired[List[str]]
    notes: NotRequired[str]


class Staging(TypedDict):
    status: Literal['pass', 'fail', 'warning']
    stage_0_present: NotRequired[bool]
    stage_1_present: NotRequired[bool]
    validation_hierarchy_followed: NotRequired[bool]
    dependency_issues: NotRequired[List[str]]
    notes: NotRequired[str]


class ParameterExtraction(TypedDict):
    status: Literal['pass', 'fail', 'warning']
    extracted_count: NotRequired[int]
    cross_checked_count: NotRequired[int]
    missing_critical: NotRequired[List[str]]
    notes: NotRequired[str]


class Assumptions(TypedDict):
    status: Literal['pass', 'fail', 'warning']
    assumption_count: NotRequired[int]
    risky_assumptions: NotRequired[List[str]]
    undocumented_gaps: NotRequired[List[str]]
    notes: NotRequired[str]


class Performance(TypedDict):
    status: Literal['pass', 'fail', 'warning']
    total_estimated_runtime_min: NotRequired[float]
    budget_min: NotRequired[float]
    risky_stages: NotRequired[List[str]]
    notes: NotRequired[str]


class MaterialValidationSetup(TypedDict):
    status: Literal['pass', 'fail', 'warning']
    materials_covered: NotRequired[List[str]]
    materials_missing: NotRequired[List[str]]
    validation_criteria_clear: NotRequired[bool]
    notes: NotRequired[str]


class OutputSpecifications(TypedDict):
    status: Literal['pass', 'fail', 'warning']
    all_stages_have_outputs: NotRequired[bool]
    figure_mappings_complete: NotRequired[bool]
    notes: NotRequired[str]


class ChecklistResults(TypedDict):
    coverage: Coverage
    digitized_data: DigitizedData
    staging: Staging
    parameter_extraction: ParameterExtraction
    assumptions: Assumptions
    performance: Performance
    material_validation_setup: NotRequired[MaterialValidationSetup]
    output_specifications: NotRequired[OutputSpecifications]


class Issue(TypedDict):
    severity: Literal['blocking', 'major', 'minor']
    category: Literal[
        'coverage',
        'staging',
        'parameters',
        'assumptions',
        'performance',
        'digitized_data',
        'material_validation',
        'output_specifications',
    ]
    description: str
    suggested_fix: str


class PlanReviewerAgentOutput(TypedDict):
    verdict: Literal['approve', 'needs_revision']
    checklist_results: ChecklistResults
    issues: NotRequired[List[Issue]]
    strengths: NotRequired[List[str]]
    revision_count: NotRequired[int]
    escalate_to_user: NotRequired[Union[bool, str]]
    summary: str
