# generated by datamodel-codegen:
#   filename:  progress_schema.json
#   timestamp: 2025-12-05T23:05:02+00:00

from __future__ import annotations

from typing import Any, Dict, List, Literal, NotRequired, Optional, TypedDict


class DiscrepancySummary(TypedDict):
    total_discrepancies: NotRequired[int]
    blocking_discrepancies: NotRequired[int]
    systematic_shifts_identified: NotRequired[List[str]]


class Output(TypedDict):
    type: Literal['data', 'plot', 'log']
    filename: str
    description: str
    target_figure: NotRequired[Optional[str]]
    result_status: NotRequired[Literal['success', 'partial', 'failure']]
    comparison_notes: NotRequired[str]


class Discrepancy(TypedDict):
    id: str
    figure: str
    quantity: str
    paper_value: str
    simulation_value: str
    difference_percent: NotRequired[float]
    classification: Literal['excellent', 'acceptable', 'investigate']
    likely_cause: NotRequired[str]
    action_taken: NotRequired[str]
    blocking: NotRequired[bool]


class Context(TypedDict):
    stage_id: NotRequired[Optional[str]]
    agent: NotRequired[str]
    reason: NotRequired[str]


class UserInteraction(TypedDict):
    id: str
    timestamp: str
    interaction_type: Literal[
        'material_checkpoint',
        'clarification',
        'trade_off_decision',
        'parameter_confirmation',
        'stop_decision',
        'backtrack_approval',
        'context_overflow',
        'general_feedback',
    ]
    context: Context
    question: NotRequired[str]
    user_response: NotRequired[str]
    impact: NotRequired[str]
    alternatives_considered: NotRequired[List[str]]


class StageProgress(TypedDict):
    stage_id: str
    stage_type: Literal[
        'MATERIAL_VALIDATION',
        'SINGLE_STRUCTURE',
        'ARRAY_SYSTEM',
        'PARAMETER_SWEEP',
        'COMPLEX_PHYSICS',
    ]
    status: Literal[
        'not_started',
        'in_progress',
        'completed_success',
        'completed_partial',
        'completed_failed',
        'blocked',
        'needs_rerun',
        'invalidated',
    ]
    invalidation_reason: NotRequired[Optional[str]]
    last_updated: str
    revision_count: NotRequired[int]
    runtime_seconds: NotRequired[float]
    summary: str
    outputs: NotRequired[List[Output]]
    discrepancies: NotRequired[List[Discrepancy]]
    issues: NotRequired[List[str]]
    next_actions: NotRequired[List[str]]
    analysis_summary: NotRequired[Optional[Dict[str, Any]]]
    analysis_result_reports: NotRequired[List[Dict[str, Any]]]
    quantitative_summary: NotRequired[List[Dict[str, Any]]]


class PaperReproductionProgress(TypedDict):
    paper_id: str
    total_runtime_seconds: NotRequired[float]
    stages: List[StageProgress]
    discrepancy_summary: NotRequired[DiscrepancySummary]
    user_interactions: NotRequired[List[UserInteraction]]
