# generated by datamodel-codegen:
#   filename:  prompt_adaptations_schema.json
#   timestamp: 2025-12-03T07:47:14+00:00

from __future__ import annotations

from typing import Dict, List, Literal, NotRequired, TypedDict


class ReproductionOutcome(TypedDict):
    success_rate: NotRequired[float]
    figures_reproduced: NotRequired[int]
    figures_total: NotRequired[int]
    overall_status: NotRequired[Literal['success', 'partial', 'failure', 'aborted']]


class Adaptation(TypedDict):
    id: str
    target_agent: Literal[
        'PromptAdaptorAgent',
        'PlannerAgent',
        'SimulationDesignerAgent',
        'CodeGeneratorAgent',
        'CodeReviewerAgent',
        'ExecutionValidatorAgent',
        'PhysicsSanityAgent',
        'ResultsAnalyzerAgent',
        'ComparisonValidatorAgent',
        'SupervisorAgent',
    ]
    target_file: NotRequired[str]
    modification_type: Literal['append', 'modify', 'remove']
    confidence: float
    content: str
    original_content: NotRequired[str]
    location: NotRequired[str]
    reason: str
    domain_specific: NotRequired[bool]
    reversible: NotRequired[bool]


class PromptAdaptationsLog(TypedDict):
    paper_id: str
    timestamp: str
    domain: str
    domain_signals: NotRequired[List[str]]
    adaptations: List[Adaptation]
    protected_files: NotRequired[List[str]]
    reproduction_outcome: NotRequired[ReproductionOutcome]
    adaptation_effectiveness: NotRequired[
        Dict[str, Literal['helpful', 'neutral', 'harmful', 'unknown']]
    ]
    lessons_learned: NotRequired[List[str]]
