# generated by datamodel-codegen:
#   filename:  report_schema.json
#   timestamp: 2025-12-03T07:47:14+00:00

from __future__ import annotations

from typing import List, Literal, NotRequired, TypedDict


class PaperCitation(TypedDict):
    authors: str
    title: str
    journal: str
    year: int
    volume: NotRequired[str]
    pages: NotRequired[str]
    doi: NotRequired[str]


class OverallAssessmentItem(TypedDict):
    aspect: str
    status: Literal['Reproduced', 'Partial', 'Not Reproduced', 'Not Attempted']
    status_icon: Literal['✅', '⚠️', '❌', '⏭️']
    notes: NotRequired[str]


class ExecutiveSummary(TypedDict):
    overall_assessment: List[OverallAssessmentItem]


class ParametersFromPaperItem(TypedDict):
    parameter: str
    value: str
    source: str


class ParametersRequiringInterpretationItem(TypedDict):
    parameter: str
    assumed_value: str
    rationale: str
    impact: Literal['Critical', 'Moderate', 'Minor']


class SimulationImplementationItem(TypedDict):
    parameter: str
    value: str


class Assumptions(TypedDict):
    parameters_from_paper: List[ParametersFromPaperItem]
    parameters_requiring_interpretation: List[ParametersRequiringInterpretationItem]
    simulation_implementation: List[SimulationImplementationItem]


class SummaryTableItem(TypedDict):
    figure: str
    main_effect: str
    effect_match: Literal['✅', '⚠️', '❌']
    shape_format: str
    format_match: Literal['✅', '⚠️', '❌']


class SystematicDiscrepancy(TypedDict):
    name: str
    description: str
    origin: str
    affected_figures: NotRequired[List[str]]


class Conclusions(TypedDict):
    main_physics_reproduced: bool
    key_findings: List[str]
    limitations: NotRequired[List[str]]
    final_statement: NotRequired[str]


class ComparisonTableItem(TypedDict):
    feature: str
    paper: str
    reproduction: str
    status: Literal['✅ Match', '⚠️ Partial', '❌ Mismatch']


class ShapeComparisonItem(TypedDict):
    aspect: str
    paper: str
    reproduction: str


class FigureComparison(TypedDict):
    figure_id: str
    title: str
    paper_image_path: NotRequired[str]
    reproduction_image_path: NotRequired[str]
    comparison_table: List[ComparisonTableItem]
    shape_comparison: List[ShapeComparisonItem]
    reason_for_difference: str


class PaperReproductionReport(TypedDict):
    paper_id: str
    paper_citation: PaperCitation
    executive_summary: ExecutiveSummary
    assumptions: Assumptions
    figure_comparisons: List[FigureComparison]
    summary_table: List[SummaryTableItem]
    systematic_discrepancies: List[SystematicDiscrepancy]
    conclusions: Conclusions
