# generated by datamodel-codegen:
#   filename:  simulation_designer_output_schema.json
#   timestamp: 2025-12-05T15:27:01+00:00

from __future__ import annotations

from typing import Any, Dict, List, Literal, NotRequired, Optional, TypedDict


class UnitSystem(TypedDict):
    characteristic_length_m: float
    length_unit: str
    example_conversions: NotRequired[Dict[str, float]]


class CellSize(TypedDict):
    x: NotRequired[float]
    y: NotRequired[float]
    z: NotRequired[float]


class Center(TypedDict):
    x: NotRequired[float]
    y: NotRequired[float]
    z: NotRequired[float]


class Structure(TypedDict):
    name: NotRequired[str]
    type: NotRequired[
        Literal['cylinder', 'sphere', 'block', 'ellipsoid', 'cone', 'prism', 'custom']
    ]
    material_ref: NotRequired[str]
    center: NotRequired[Center]
    dimensions: NotRequired[Dict[str, Any]]
    real_dimensions: NotRequired[Dict[str, Any]]


class Symmetry(TypedDict):
    direction: NotRequired[Literal['x', 'y', 'z']]
    phase: NotRequired[float]


class Geometry(TypedDict):
    dimensionality: NotRequired[Literal['2D', '3D']]
    cell_size: NotRequired[CellSize]
    resolution: NotRequired[float]
    structures: NotRequired[List[Structure]]
    symmetries: NotRequired[List[Symmetry]]


class DrudeTerm(TypedDict):
    omega_p: NotRequired[float]
    gamma: NotRequired[float]


class LorentzTerm(TypedDict):
    sigma: NotRequired[float]
    omega_0: NotRequired[float]
    gamma: NotRequired[float]


class Parameters(TypedDict):
    epsilon: NotRequired[float]
    epsilon_inf: NotRequired[float]
    drude_terms: NotRequired[List[DrudeTerm]]
    lorentz_terms: NotRequired[List[LorentzTerm]]


class WavelengthRange(TypedDict):
    min_nm: NotRequired[float]
    max_nm: NotRequired[float]


class Material(TypedDict):
    id: str
    name: str
    model_type: Literal['constant', 'tabulated', 'drude', 'lorentz', 'drude_lorentz']
    source: NotRequired[str]
    data_file: NotRequired[Optional[str]]
    parameters: NotRequired[Parameters]
    wavelength_range: NotRequired[WavelengthRange]


class Size(TypedDict):
    x: NotRequired[float]
    y: NotRequired[float]
    z: NotRequired[float]


class Source(TypedDict):
    type: Literal['gaussian', 'continuous', 'eigenmode']
    component: NotRequired[Literal['Ex', 'Ey', 'Ez', 'Hx', 'Hy', 'Hz']]
    center: Center
    size: Size
    wavelength_center_nm: NotRequired[float]
    wavelength_width_nm: NotRequired[float]
    frequency_center_meep: NotRequired[float]
    frequency_width_meep: NotRequired[float]


class BoundaryConditions(TypedDict):
    x_min: NotRequired[Literal['pml', 'periodic', 'mirror', 'metallic']]
    x_max: NotRequired[Literal['pml', 'periodic', 'mirror', 'metallic']]
    y_min: NotRequired[Literal['pml', 'periodic', 'mirror', 'metallic']]
    y_max: NotRequired[Literal['pml', 'periodic', 'mirror', 'metallic']]
    z_min: NotRequired[Literal['pml', 'periodic', 'mirror', 'metallic']]
    z_max: NotRequired[Literal['pml', 'periodic', 'mirror', 'metallic']]
    pml_thickness: NotRequired[float]
    pml_layers: NotRequired[int]


class Monitor(TypedDict):
    type: Literal['flux', 'field', 'dft_fields', 'near2far']
    name: str
    purpose: NotRequired[str]
    center: NotRequired[Center]
    size: NotRequired[Size]
    frequency_points: NotRequired[int]


class RunUntil(TypedDict):
    type: NotRequired[Literal['time', 'decay']]
    value: NotRequired[float]
    decay_by: NotRequired[float]


class SimulationParameters(TypedDict):
    run_until: NotRequired[RunUntil]
    subpixel_averaging: NotRequired[bool]
    force_complex_fields: NotRequired[bool]


class PerformanceEstimate(TypedDict):
    runtime_estimate_minutes: float
    memory_estimate_gb: float
    total_cells: NotRequired[int]
    timesteps_estimate: NotRequired[int]
    notes: NotRequired[str]


class OutputSpecification(TypedDict):
    artifact_type: NotRequired[
        Literal[
            'spectrum_csv',
            'field_data_npz',
            'field_plot_png',
            'spectrum_plot_png',
            'dispersion_csv',
            'raw_h5',
        ]
    ]
    filename_pattern: NotRequired[str]
    description: NotRequired[str]
    columns: NotRequired[List[str]]


class NewAssumption(TypedDict):
    id: NotRequired[str]
    category: NotRequired[str]
    description: NotRequired[str]
    reason: NotRequired[str]
    critical: NotRequired[bool]


class SimulationDesignerAgentOutput(TypedDict):
    stage_id: str
    design_description: str
    unit_system: UnitSystem
    geometry: Geometry
    materials: List[Material]
    sources: List[Source]
    boundary_conditions: BoundaryConditions
    monitors: List[Monitor]
    simulation_parameters: NotRequired[SimulationParameters]
    performance_estimate: PerformanceEstimate
    output_specifications: NotRequired[List[OutputSpecification]]
    new_assumptions: NotRequired[List[NewAssumption]]
    design_rationale: NotRequired[str]
    potential_issues: NotRequired[List[str]]
    summary: str
