# generated by datamodel-codegen:
#   filename:  supervisor_output_schema.json
#   timestamp: 2025-12-03T07:47:14+00:00

from __future__ import annotations

from typing import List, Literal, NotRequired, TypedDict


class ValidationHierarchyStatus(TypedDict):
    material_validation: Literal['passed', 'partial', 'failed', 'not_done']
    single_structure: Literal['passed', 'partial', 'failed', 'not_done']
    arrays_systems: Literal['passed', 'partial', 'failed', 'not_done']
    parameter_sweeps: Literal['passed', 'partial', 'failed', 'not_done']


class MainPhysicsAssessment(TypedDict):
    physics_plausible: bool
    conservation_satisfied: bool
    value_ranges_reasonable: bool
    systematic_issues: NotRequired[List[str]]
    notes: NotRequired[str]


class ErrorAnalysis(TypedDict):
    error_type: NotRequired[Literal['systematic', 'random', 'none']]
    error_persistence: NotRequired[
        Literal['improving', 'stable', 'worsening', 'not_applicable']
    ]
    root_cause_hypothesis: NotRequired[str]
    confidence: NotRequired[Literal['high', 'medium', 'low']]


class Recommendation(TypedDict):
    action: str
    priority: Literal['critical', 'high', 'medium', 'low']
    rationale: NotRequired[str]


class BacktrackDecision(TypedDict):
    accepted: bool
    target_stage_id: str
    stages_to_invalidate: List[str]
    reason: str


class ProgressSummary(TypedDict):
    stages_completed: NotRequired[int]
    stages_remaining: NotRequired[int]
    overall_confidence: NotRequired[Literal['high', 'medium', 'low']]
    key_achievements: NotRequired[List[str]]
    key_blockers: NotRequired[List[str]]


class SupervisorAgentOutput(TypedDict):
    verdict: Literal[
        'ok_continue',
        'replan_needed',
        'change_priority',
        'ask_user',
        'backtrack_to_stage',
        'all_complete',
    ]
    validation_hierarchy_status: ValidationHierarchyStatus
    main_physics_assessment: MainPhysicsAssessment
    error_analysis: NotRequired[ErrorAnalysis]
    recommendations: NotRequired[List[Recommendation]]
    backtrack_decision: NotRequired[BacktrackDecision]
    user_question: NotRequired[str]
    progress_summary: NotRequired[ProgressSummary]
    should_stop: NotRequired[bool]
    stop_reason: NotRequired[str]
    summary: str
